/*
Suppression des tables de signalisation routières
*/

-- 1. Suppression des tables/VM temporaires
DROP TABLE G_BASE_VOIE.TA_SIGNALISATION_RELATION_FAMILLE_LIBELLE CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TA_SIGNALISATION_RELATION_LIBELLE CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TA_SIGNALISATION_LIBELLE CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TA_SIGNALISATION_FAMILLE CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TA_SIGNALISATION_MARQUAGE_LINEAIRE CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TA_SIGNALISATION_MARQUAGE_PONCTUEL CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TA_SIGNALISATION_MARQUAGE_SURFACIQUE CASCADE CONSTRAINTS;
DROP TABLE G_BASE_VOIE.TA_SIGNALISATION_AGENT CASCADE CONSTRAINTS;

-- 2. Suppression des métadonnées spatiales des tables temporaires
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_SIGNALISATION_MARQUAGE_LINEAIRE';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_SIGNALISATION_MARQUAGE_PONCTUEL';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TA_SIGNALISATION_MARQUAGE_SURFACIQUE';
COMMIT;

