-- Suppression des tables d'import de la signalisation horizontale
DROP TABLE TOTO_SIGNALISATION_MEL_SH_LONGITUDINALE CASCADE CONSTRAINTS;
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TOTO_SIGNALISATION_MEL_SH_LONGITUDINALE';
DROP TABLE TEMP_SIGNALISATION_MEL_SH_LONGITUDINALE CASCADE CONSTRAINTS;
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TEMP_SIGNALISATION_MEL_SH_LONGITUDINALE';
DROP TABLE TEMP_SIGNALISATION_MEL_SH_MARQ_SECURITE CASCADE CONSTRAINTS;
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TEMP_SIGNALISATION_MEL_SH_MARQ_SECURITE';
DROP TABLE TEMP_SIGNALISATION_MEL_SH_PLACE_PMR CASCADE CONSTRAINTS;
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TEMP_SIGNALISATION_MEL_SH_PLACE_PMR';
DROP TABLE TEMP_SIGNALISATION_MEL_SH_SAS_CYCLABLE CASCADE CONSTRAINTS;
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TEMP_SIGNALISATION_MEL_SH_SAS_CYCLABLE';
DROP TABLE TEMP_SIGNALISATION_MEL_SH_SURF_MARQUE CASCADE CONSTRAINTS;
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TEMP_SIGNALISATION_MEL_SH_SURF_MARQUE';
DROP TABLE TEMP_SIGNALISATION_PONCTUELLE CASCADE CONSTRAINTS;
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'TEMP_SIGNALISATION_PONCTUELLE';
COMMIT;
 
/

